version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:NPW*N04l0K@postgres:5432/naukograd
      NODE_ENV: development
      PORT: 3000
    ports:
      - "4001:4001"
    command: npm run generate-and-start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: NPW*N04l0K
      POSTGRES_DB: naukograd
